// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrenominaApi.Data;

#nullable disable

namespace PrenominaApi.Data.Migrations.Prenomina
{
    [DbContext(typeof(PrenominaDbContext))]
    [Migration("20250330041334_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.AssistanceIncident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit")
                        .HasColumnName("approved");

                    b.Property<Guid>("ByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("by_user_id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EmployeeCode")
                        .HasColumnType("int")
                        .HasColumnName("employee_code");

                    b.Property<string>("IncidentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("incident_code");

                    b.Property<bool>("TimeOffRequest")
                        .HasColumnType("bit")
                        .HasColumnName("time_off_request");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ByUserId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Date");

                    b.HasIndex("EmployeeCode");

                    b.HasIndex("IncidentCode");

                    b.ToTable("assistance_incident");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.AssistanceIncidentApprover", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("ApprovalDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("approval_date");

                    b.Property<Guid>("AssistanceIncidentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assistance_incident_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("IncidentApproverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("incident_approver_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AssistanceIncidentId");

                    b.HasIndex("IncidentApproverId");

                    b.ToTable("assistance_incident_approver");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_value");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("record_id");

                    b.Property<string>("SectionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("section_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ByUserId");

                    b.ToTable("audit_log");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.EmployeeCheckIns", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<TimeOnly>("CheckIn")
                        .HasColumnType("time")
                        .HasColumnName("check_in");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EmployeeCode")
                        .HasColumnType("int")
                        .HasColumnName("employee_code");

                    b.Property<int>("EmployeeSchedule")
                        .HasColumnType("int")
                        .HasColumnName("employee_schedule");

                    b.Property<int>("EoS")
                        .HasColumnType("int")
                        .HasColumnName("EoS");

                    b.Property<string>("NumConc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("num_conc");

                    b.Property<int>("Period")
                        .HasColumnType("int")
                        .HasColumnName("period");

                    b.Property<int>("TypeNom")
                        .HasColumnType("int")
                        .HasColumnName("type_nom");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("EmployeeCode");

                    b.ToTable("employee_check_ins");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.IncidentApprover", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IncidentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("incident_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IncidentCode");

                    b.HasIndex("UserId");

                    b.ToTable("incident_approver");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.IncidentCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ExternalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("external_code");

                    b.Property<bool>("IsAdditional")
                        .HasColumnType("bit")
                        .HasColumnName("is_additional");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("label");

                    b.Property<Guid?>("MetadataId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("metadata_id");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<bool>("RequiredApproval")
                        .HasColumnType("bit")
                        .HasColumnName("required_approval");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<bool>("WithOperation")
                        .HasColumnType("bit")
                        .HasColumnName("with_operation");

                    b.HasKey("Code");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("MetadataId")
                        .IsUnique()
                        .HasFilter("[metadata_id] IS NOT NULL");

                    b.ToTable("incident_code");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.IncidentCodeMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("amount");

                    b.Property<int>("ColumnForOperation")
                        .HasColumnType("int")
                        .HasColumnName("column_for_operation");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("CustomValue")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("custom_value");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<int>("MathOperation")
                        .HasColumnType("int")
                        .HasColumnName("math_operation");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("incident_code_metadata");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("label");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.Section", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Code");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("section");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.SystemConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("data");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Key");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("system_config");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("user");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.UserCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_company");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.UserDepartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("department_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserCompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_company_id");

                    b.HasKey("Id");

                    b.HasIndex("UserCompanyId");

                    b.ToTable("user_department");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.UserSupervisor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int")
                        .HasColumnName("supervisor_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserCompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_company_id");

                    b.HasKey("Id");

                    b.HasIndex("UserCompanyId");

                    b.ToTable("user_supervisor");
                });

            modelBuilder.Entity("RoleSection", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SectionsCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RolesId", "SectionsCode");

                    b.HasIndex("SectionsCode");

                    b.ToTable("section_rol", (string)null);
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.AssistanceIncident", b =>
                {
                    b.HasOne("PrenominaApi.Models.Prenomina.User", "User")
                        .WithMany("AssistanceIncidents")
                        .HasForeignKey("ByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrenominaApi.Models.Prenomina.IncidentCode", "ItemIncidentCode")
                        .WithMany("AssistanceIncidents")
                        .HasForeignKey("IncidentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemIncidentCode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.AssistanceIncidentApprover", b =>
                {
                    b.HasOne("PrenominaApi.Models.Prenomina.AssistanceIncident", "AssistanceIncident")
                        .WithMany("AssistanceIncidentApprover")
                        .HasForeignKey("AssistanceIncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrenominaApi.Models.Prenomina.IncidentApprover", "IncidentApprover")
                        .WithMany("AssistanceIncidentApprover")
                        .HasForeignKey("IncidentApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssistanceIncident");

                    b.Navigation("IncidentApprover");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.AuditLog", b =>
                {
                    b.HasOne("PrenominaApi.Models.Prenomina.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.IncidentApprover", b =>
                {
                    b.HasOne("PrenominaApi.Models.Prenomina.IncidentCode", "ItemIncidentCode")
                        .WithMany("IncidentApprovers")
                        .HasForeignKey("IncidentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrenominaApi.Models.Prenomina.User", "User")
                        .WithMany("IncidentApprovers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemIncidentCode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.IncidentCode", b =>
                {
                    b.HasOne("PrenominaApi.Models.Prenomina.IncidentCodeMetadata", "IncidentCodeMetadata")
                        .WithOne("IncidentCode")
                        .HasForeignKey("PrenominaApi.Models.Prenomina.IncidentCode", "MetadataId");

                    b.Navigation("IncidentCodeMetadata");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.User", b =>
                {
                    b.HasOne("PrenominaApi.Models.Prenomina.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.UserCompany", b =>
                {
                    b.HasOne("PrenominaApi.Models.Prenomina.User", "User")
                        .WithMany("Companies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.UserDepartment", b =>
                {
                    b.HasOne("PrenominaApi.Models.Prenomina.UserCompany", "UserCompany")
                        .WithMany("UserDepartments")
                        .HasForeignKey("UserCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserCompany");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.UserSupervisor", b =>
                {
                    b.HasOne("PrenominaApi.Models.Prenomina.UserCompany", "UserCompany")
                        .WithMany("UserSupervisors")
                        .HasForeignKey("UserCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserCompany");
                });

            modelBuilder.Entity("RoleSection", b =>
                {
                    b.HasOne("PrenominaApi.Models.Prenomina.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrenominaApi.Models.Prenomina.Section", null)
                        .WithMany()
                        .HasForeignKey("SectionsCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.AssistanceIncident", b =>
                {
                    b.Navigation("AssistanceIncidentApprover");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.IncidentApprover", b =>
                {
                    b.Navigation("AssistanceIncidentApprover");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.IncidentCode", b =>
                {
                    b.Navigation("AssistanceIncidents");

                    b.Navigation("IncidentApprovers");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.IncidentCodeMetadata", b =>
                {
                    b.Navigation("IncidentCode");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.User", b =>
                {
                    b.Navigation("AssistanceIncidents");

                    b.Navigation("AuditLogs");

                    b.Navigation("Companies");

                    b.Navigation("IncidentApprovers");
                });

            modelBuilder.Entity("PrenominaApi.Models.Prenomina.UserCompany", b =>
                {
                    b.Navigation("UserDepartments");

                    b.Navigation("UserSupervisors");
                });
#pragma warning restore 612, 618
        }
    }
}
